#!/bin/bash

check-battery () {
 while [[ $(pmset -g batt | grep -v $1% | grep -v "Now drawing") ]]; do
    sleep 1
  done
  text="\"Your computer has reached $1%!\""
  cmd="display notification ${text} with title \"All Done!\""
  osascript -e "${cmd}"
}

check-battery $1 &>/dev/null &
